// code generated by [generate-resource-dart-code] vscode-extension.
class AssetsImages {
  static const googleOutlinePng = 'assets/images/google_outline.png';
  static const logoPng = 'assets/images/logo.png';
  static const logo_200Jpg = 'assets/images/logo_200.jpg';
  static const logo_400Jpg = 'assets/images/logo_400.jpg';
  static const pdfPng = 'assets/images/pdf.png';
}

class AssetsSvgs {

}

